# Generated by Django 4.2.6 on 2023-10-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
                ('mail', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=8)),
                ('registered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
