# Generated by Django 4.2.6 on 2023-10-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_developer_guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
