# Generated by Django 4.2.6 on 2023-11-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_developer_guide', '0003_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='created_by',
        ),
    ]
