# Generated by Django 4.2.6 on 2023-11-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_developer_guide', '0004_rename_descricao_categories_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='created_by',
            field=models.TextField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
