# Generated by Django 4.2.6 on 2023-11-15 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_developer_guide', '0005_categories_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patterns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('registered', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(max_length=50)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_developer_guide.categories')),
            ],
        ),
    ]
